### ISSUE TITLE
Get rid of postinstall script

### ISSUE THREAD

**Issue by notslang** [sulu-one/sulu#36]
The application shouldn't have sub-dependencies - it breaks dependency mapping within npm, makes the assumption that post-install scripts have permission to install deps (and are being allowed to run), breaks normal update functions, and complicates the install process.

**Comment by s-a** [comment]
I d like too improve this too. It is an artifact from splitting codes into seperate packages. To resolve this issue we need to move all dependencies to the regarding [packages](https://github.com/sulu-one/sulu/blob/master/docs/packages.md#preinstalled). 

For readers who have switched on later: This affects "only" development environment.

**Comment by s-a** [comment]
postinstall is indispensable so far we need a seperate process to install (later) unpacked dependencies.
